### ISSUE TITLE
Support JSX compilation

### ISSUE THREAD

**Issue by aomarks** [google/playground-elements#100]
TypeScript can compile TSX (`.tsx` files, maybe `jsx` files too?).

**Comment by jpoehnelt** [comment]
> TypeScript ships with three JSX modes: preserve, react, and react-native

I imagine the only one that would work is react as preserve would require a second step.

**Comment by jpoehnelt** [comment]
https://www.typescriptlang.org/docs/handbook/jsx.html seems there are a few more config values for `{ jsx: ...}` that might be possible.

**Comment by taylor-vann** [comment]
https://github.com/google/playground-elements/pull/319
