### ISSUE TITLE
Move playground-elements to Google org

### ISSUE THREAD

**Issue by codecycletechnologies** [google/playground-elements#132]
Hello

This project is heart of docs for new lit website and also built with lit only.
So it will be nice for developers to map it and understand easily the power of lit & playground-elements.

Also we can rename this repo to playground only as such element words make so much confusion in normal web tech world in communication so to make it clear in communication playground word only will be nice.

Thanks.

**Comment by codecycletechnologies** [comment]
@aomarks please share your views...thanks

**Comment by codecycletechnologies** [comment]
@aomarks alright get it...one suggested name is codeground if you like it.
Thanks

**Comment by aomarks** [comment]
This repo is now in the Google GitHub org
