### ISSUE TITLE
Codecompletion

### ISSUE THREAD

**Issue by Matsuuu** [google/playground-elements#203]
Heya,

Awesome work so far with the playground elements. I'd love to contribute to this as I'll most likely be adopting playground-elements as the code editing/inspection platform for [Web Component DevTools](https://github.com/Matsuuu/web-component-devtools).

I was wondering if there is plans, or if there is a reason there's no code completion in playground elements? I know it can be a bit heavier to implement, but seeing that [Codemirror has examples on how to do it](https://codemirror.net/demo/complete.html), it would be possible.

If not built in, would there be interest in a addon to enable intellisense/autocompletion to playgrounds?

I'd be happy to work on that since it's something I'd want in some of my own personal projects too

**Comment by aomarks** [comment]
> Heya,
> 
> Awesome work so far with the playground elements. I'd love to contribute to this as I'll most likely be adopting playground-elements as the code editing/inspection platform for [Web Component DevTools](https://github.com/Matsuuu/web-component-devtools).

Awesome!

> I was wondering if there is plans, or if there is a reason there's no code completion in playground elements? I know it can be a bit heavier to implement, but seeing that [Codemirror has examples on how to do it](https://codemirror.net/demo/complete.html), it would be possible.

No particular reason it hasn't been worked on yet, just lack of time among many other priorities.

> If not built in, would there be interest in a addon to enable intellisense/autocompletion to playgrounds?
> 
> I'd be happy to work on that since it's something I'd want in some of my own personal projects too

Yeah, I think that would be great!

(Personally the thing I miss even more than code-completion coming from VSCode is getting documentation/types when I hover over something. I think that's all part of the same family of intellisense-related queries to the TypeScript language server, though, so if we can get one working, the other should be simple too.)

I think the main obstacle to getting this working is going to be on the worker side. We currently create a new TypeScript language service instance for every compile (https://github.com/PolymerLabs/playground-elements/blob/e5cb8462fbdfa1238b919705d4738a795b5453a9/src/typescript-worker/typescript.ts#L88). What we should do instead is have a persistent language service per project worker, and keep track of which files have changed between compiles. I believe we could then query this persistent language service (we'd need a new <playground-project> -> worker API for this) for intellisense-related info. This would also enable incremental compilation, which would be very beneficial for compilation performance.
