### ISSUE TITLE
import @types/... packages

### ISSUE THREAD

**Issue by jpoehnelt** [google/playground-elements#246]
Is there a mechanism to load the types for a package that are not bundled, e.g. @types/foo. I didn't see anything in the documentation and my quick experimentation in the playground with different formats did not yield anything. 

Might need to add support for typeReferenceDirectives and allow for triple slash directives?

**Comment by aomarks** [comment]
There is currently no mechanism to do this, but I agree it is a feature we should support.

I think it would be nice to automatically fetch the @types package corresponding to a dependency if it doesn't appear to have its own typings.

**Comment by jpoehnelt** [comment]
I also have the case where there is no NPM installable package (Google Maps) but there is a @types/google.maps.

**Comment by augustjk** [comment]
Some CDNs like https://esm.sh and skypack (with `?dts` query) provide the `X-Typescript-Types` header with location to `.d.ts` for Deno compatibility https://deno.land/manual@v1.11.5/typescript/types#using-x-typescript-types-header. Perhaps we could take advantage of that?

It unfortunately doesn't help with type only packages though.
