### ISSUE TITLE
`playground-hide` adds empty values on the undo history.

### ISSUE THREAD

**Issue by AndrewJakubowicz** [google/playground-elements#267]
### Context

The logic for folding sets undo history that clears the file.
https://github.com/google/playground-elements/blob/51fa356543916631cc288a50d62b1ca388a20d1b/src/playground-code-editor.ts#L776

For repro, there is a test linking this issue number reproducing the bug.

This behavior can also be viewed on lit.dev, with the clock example. Navigate to [my-timer.ts](https://lit.dev/docs/), and change the file returning to `my-timer`. On undoing notice empty contents included in the undo stack.

**Comment by AndrewJakubowicz** [comment]
Follow up from https://github.com/google/playground-elements/pull/281.

This PR introduces a behavior in CodeMirror where any readonly block will clear the history. Therefore the original issue no longer reproduces.

Next steps:

 - Should this edge case be documented?
 - Update test so this case is tested. Then if CodeMirror changes this behavior we'll know.
 - Maybe programmatic `.value` property updates should always clear history?

**Comment by Matsuuu** [comment]
I would be going for number 2 or 3, or even both.

Having a test to track if this changes in the future, especially if we end up updating CodeMirror to the latest version would be great.

The situation where the value can be updated from the outside usually is one in which the content drastically changes, and in my opinion in these situations, it could be beneficial to clear the history.

I wonder if this will affect functionality with the playgrounds-ide though as the content is swapped when changing files, will the undo history just be erased when opened files are changed and changed back?

**Comment by AndrewJakubowicz** [comment]
Agreed!

>I wonder if this will affect functionality with the playgrounds-ide though as the content is swapped when changing files, will the undo history just be erased when opened files are changed and changed back?

I manually tested the last case, and _think_ it works correctly because we:

1. Scope the history per virtual file.
2. Only set the fold/hide region on the initial `.value` setting of the virtual file (when the document instance is created).

Tested by updating configurator to have a folded region. Then edited beneath it - changed files a bit. Then checked that undo worked after swapping files.

However if later `value` is programmatically changed, it will clear the history (number 3).

**Comment by Matsuuu** [comment]
I think if the cases you listed you tested work well, it would be 100% fine to clear the history on an external programmatic `value` change, as how I see it, the `value` change usually means "turning a new page" and changing the content/context, therefore it makes sense to ditch the history too

**Comment by AndrewJakubowicz** [comment]
Whilst working on https://github.com/google/playground-elements/pull/295 I realized that I had missed that we could make the `readonly` configurable and not make the comments readonly.

And then I also found the root cause of this initial bug - which was due to a hacky way that the fold/hide regions were being reset by using the codemirror value.
