### ISSUE TITLE
Incorrect event name 'changed'

### ISSUE THREAD

**Issue by rwalle** [google/playground-elements#296]
In line 782 of `README.md`
https://github.com/google/playground-elements/blob/50f58007717b41dd06bdaf9093140dff4f5e6386/README.md?plain=1#L782
The event name is written as `changed` which is incorrect, as the `Event` in the source code uses the name `change`
https://github.com/google/playground-elements/blob/50f58007717b41dd06bdaf9093140dff4f5e6386/src/playground-code-editor.ts#L493

btw on line 811 of `README.md`
https://github.com/google/playground-elements/blob/50f58007717b41dd06bdaf9093140dff4f5e6386/README.md?plain=1#L811
a closing bracket is missing

I normally would create a pull request and correct this, but I need my employer's approval for signing the CLA. I was advised to create an issue instead. I know this is not an ideal situation. I would be very grateful if the maintainer or someone else could pick this up.

Thanks

**Comment by AndrewJakubowicz** [comment]
Thanks for the issue! Great catch. I can look into this!

**Comment by AndrewJakubowicz** [comment]
Thank you!

**Comment by rwalle** [comment]
Thank you!
