### ISSUE TITLE
Add ability to focus a specific file when loading project

### ISSUE THREAD

**Issue by kevinpschaaf** [google/playground-elements#303]
Proposal: Add a flag in the `project.json` `files` options to indicate a specific file in the project should be focused when a project is loaded.

e.g.
```json
{
  "files": {
    "index.html": {},
    "foo.ts": { "selected": true },
    "bar.ts": {}
  }
}
```

This is useful when using `playground-elements` in a tutorial flow, in order to direct a user to edit a specific file in the project.

**Comment by AndrewJakubowicz** [comment]
Maybe unrelated - noting as may be relevant to this investigation. In the tutorial flow if a file is added and focused. If the user then goes to a prior part where that file doesn't exist, it remains open but with no content. This may be out of scope of playground-elements.
